### ISSUE TITLE
Review test 

### ISSUE THREAD

**Issue by nimplay** [lucas-crodrigues/todo-list#6]
All test work correctly congrats

**Comment by jaferIdrees** [comment]
### Highlights

- JEST was used wisely. 💯 
- Testing covered the required functionality to be tested 👍 

**I have the below comments:**
- It would be better if you create a new folder for testing.
- In the below section it seems you are creating new functionality, I beleive you need to test the functionality that you already have.
- https://github.com/lucas-crodrigues/todo-list/blob/518883f8f63683b32a803c8505addecd31beacd1/src/modules/functions.test.js#L48-L52

**Comment by lucas-crodrigues** [comment]
thank you for the feedback @jaferIdrees @nimplay
